[WIP] Add API to read & write registers
headcrab-rs/headcrab pull request #98
Opened 2020-08-29 21:39 UTC by nbaksalyar

Implements #87.

- [ ] Add trait definition.
- [ ] Implement register functions for the Linux target.
- [ ] Refactor the repl example to use the new API.

2020-11-25 09:21 UTC, bjorn3 requested changes

2020-11-25 09:21 UTC, bjorn3 commented on examples/repl.rs
>      struct X86_64EvalContext {
```suggestion
    struct EvalContext {
```
This is no longer x86_64 specific.

2020-11-25 09:21 UTC, bjorn3 commented on src/target/linux.rs
> +type BoxedLinuxThread = Box<dyn Thread<RegistersX86_64, ThreadId = i32>>;
Should get a `#[cfg]` as the register type depends on the target.

2020-11-25 23:51 UTC, nbaksalyar commented
@bjorn3 should be fixed now, thanks!

2020-11-26 06:37 UTC, bjorn3 approved these changes

2020-11-26 06:38 UTC, merged